import type { SkillSchema, Constraint } from '../types/index.js';
import type { ProgressiveConfig, ConstraintDetail } from '../types/progressive.js';

export function generateMinimalMarkdown(
  schema: SkillSchema,
  config: ProgressiveConfig
): string {
  const lines: string[] = [];

  lines.push(`# ${schema.meta.name}`);
  lines.push('');
  lines.push(`**Version**: ${schema.meta.version}`);
  lines.push(`**Triggers**: ${schema.triggers.map(t => t.type).join(', ')}`);
  lines.push('');

  lines.push('## Steps');
  lines.push('');
  for (const step of schema.steps) {
    lines.push(`### ${step.id}`);
    lines.push(`**Action**: ${step.action || step.type}`);
    if (step.condition) {
      lines.push(`**When**: ${step.condition}`);
    }
    if (step.next_step_on_success) {
      lines.push(`**Next**: ${step.next_step_on_success} [✓]`);
    }
    if (step.next_step_on_failure) {
      lines.push(`**On Fail**: ${step.next_step_on_failure} [✗]`);
    }
    lines.push('');
  }

  lines.push('## Constraints');
  lines.push('');
  lines.push('| ID | Level | Summary |');
  lines.push('|----|-------|---------|');
  for (const c of schema.constraints) {
    const summary = extractSummary(c.description);
    lines.push(`| ${c.id} | ${c.level} | ${summary} |`);
  }
  lines.push('');

  if (config.enabled && config.generateConstraintFiles) {
    lines.push('---');
    lines.push('');
    lines.push('> 📎 Constraint details: `./constraints/`');
    lines.push('> 📖 Full documentation: `./SKILL.full.md`');
  }

  return lines.join('\n');
}

function extractSummary(description: string): string {
  const firstSentence = description.split(/[。.!；]/)[0] || description;
  if (firstSentence.length > 60) {
    return firstSentence.substring(0, 57) + '...';
  }
  return firstSentence;
}

export function generateFullMarkdown(
  schema: SkillSchema,
  sourceFile?: string
): string {
  const lines: string[] = [];

  lines.push(`# ${schema.meta.name}`);
  lines.push('');
  lines.push(`**Version**: ${schema.meta.version}`);
  if (sourceFile) {
    lines.push(`**Source**: ${sourceFile}`);
  }
  lines.push(`**Generated**: ${new Date().toISOString().split('T')[0]}`);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Overview');
  lines.push('');
  lines.push(schema.meta.description || `${schema.meta.name} 是一个标准操作流程 Skill。`);
  lines.push('');

  lines.push('## Triggers');
  lines.push('');
  lines.push('| Type | Name | Description |');
  lines.push('|------|------|-------------|');
  for (const trigger of schema.triggers) {
    lines.push(`| ${trigger.type} | ${trigger.name || '-'} | ${trigger.description || '-'} |`);
  }
  lines.push('');

  lines.push('## Steps');
  lines.push('');
  for (let i = 0; i < schema.steps.length; i++) {
    const step = schema.steps[i];
    lines.push(`### Step ${i + 1}: ${step.name}`);
    lines.push('');
    lines.push(step.description);
    lines.push('');
    if (step.condition) {
      lines.push(`**Condition**: ${step.condition}`);
    }
    lines.push(`**Action**: ${step.action || step.type}`);
    lines.push('');
  }

  if (schema.constraints.length > 0) {
    lines.push('## Constraints');
    lines.push('');
    const byLevel = groupByLevel(schema.constraints);
    for (const [level, items] of Object.entries(byLevel)) {
      const label = {
        MUST: 'MUST（必须遵守）',
        SHOULD: 'SHOULD（应当遵守）',
        MAY: 'MAY（可以遵守）',
      }[level];
      lines.push(`### ${label}`);
      lines.push('');
      for (const c of items) {
        lines.push(`- **${c.id}**: ${c.description}`);
        if (c.roles && c.roles.length > 0) {
          lines.push(`  - Roles: ${c.roles.join(', ')}`);
        }
      }
      lines.push('');
    }
  }

  if (schema.decisions && schema.decisions.length > 0) {
    lines.push('## Decisions');
    lines.push('');
    for (const decision of schema.decisions) {
      lines.push(`### ${decision.name}`);
      lines.push('');
      lines.push(`**Inputs**: ${decision.inputVars.join(', ')}`);
      lines.push(`**Outputs**: ${decision.outputVars.join(', ')}`);
      lines.push('');
      lines.push('**Rules**:');
      for (const rule of decision.rules) {
        const condition = typeof rule.when === 'object' ? rule.when.condition : rule.when;
        const action = typeof rule.then === 'object' ? rule.then.action : rule.then;
        lines.push(`- If ${condition} → ${action}`);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push(`*Generated by sop-to-skill*`);

  return lines.join('\n');
}

export function generateConstraintDetail(
  constraint: Constraint,
  sourceFile?: string
): ConstraintDetail {
  return {
    id: constraint.id,
    level: constraint.level,
    original: constraint.description,
    semantic: constraint.description,
    condition: constraint.condition,
    action: constraint.action,
    roles: constraint.roles,
    source: sourceFile ? { file: sourceFile } : undefined,
  };
}

export function constraintDetailToMarkdown(detail: ConstraintDetail): string {
  const lines: string[] = [];

  lines.push(`# ${detail.id}: ${extractSummary(detail.original)}`);
  lines.push('');
  lines.push(`**Level**: ${detail.level}`);
  lines.push('');
  lines.push('## Original Requirement');
  lines.push('');
  lines.push(detail.original);
  lines.push('');

  if (detail.semantic) {
    lines.push('## Semantic');
    lines.push('');
    lines.push(detail.semantic);
    lines.push('');
  }

  if (detail.condition) {
    lines.push('**Condition**: ' + detail.condition);
    lines.push('');
  }

  if (detail.action) {
    lines.push('**Action**: ' + detail.action);
    lines.push('');
  }

  if (detail.roles && detail.roles.length > 0) {
    lines.push('**Roles**: ' + detail.roles.join(', '));
    lines.push('');
  }

  if (detail.source) {
    lines.push('## Source');
    lines.push('');
    lines.push(`File: ${detail.source.file}`);
    if (detail.source.section) {
      lines.push(`Section: ${detail.source.section}`);
    }
    if (detail.source.line) {
      lines.push(`Line: ${detail.source.line}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function groupByLevel(constraints: Constraint[]): Record<string, Constraint[]> {
  const groups: Record<string, Constraint[]> = {
    MUST: [],
    SHOULD: [],
    MAY: [],
  };
  for (const c of constraints) {
    if (groups[c.level]) {
      groups[c.level].push(c);
    }
  }
  return groups;
}
